# Generated by Django 4.0.2 on 2022-02-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_user_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
