# Generated by Django 4.0.2 on 2022-02-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
